language: node_js
node_js:
- lts/*
- node
cache: yarn
install: yarn
script:
- yarn xo
- yarn test
- yarn build
deploy:
  provider: npm
  email: mariosant@sent.com
  api_key:
    secure: tkSVu6HGfi7JNCfh5TysJ71mPRv6xIM1U9HFsfOw96JvtHXQHA9wd4EOb3+6zWodRY1KfbAD3PC6450GBiDMhtqGa94uo6eoAdjAXc4YHz0RavDWOu/xkpidIFc/R0ytpFeZExNUy9m4L0n5xyLp6CvHvKbELIPIJEtIcMZq3JZ1cJK3QmIGfWhm+bPFe/uq3sUpkEEq9aCnOBrDjndj+I6lWlre1Nfe8h5k+HB5N13NtY07MrnGhLgCVg5/H4YZ1IlxLLyvLnHyd3k27GeduKIKNgo3qz3/faD0GLmiY8r7Dcd2LuZAEnYocg9pWXhlKWHfLodBn+h8h/I/dfj/U877lmNthhoeUwAPt3YLfQvzQDmn0QHxxICPf/0YD/d0DOj2wcb6q7bkCG0gDCWAYP4qCiiFuRXnCWh/SsXRHYcftltcMLO+8B4IXjDA+BfqvpDg/71Jjp90BhoGEIPbCfriazg97+nLrs0vERS4969DYkaMUJhRRlm/l8Nq/kujFX9N156KaX7yr5QMUA5FYnZ7pjPScpZSps6DmhUb6ygsjnA3fc5tn5ZGOy826nuLIoRvqZrOxOGHstgboYaaPPPIV4WQ8EKOfbF9TJgcn8iPYPk0pIblhegYbXuvktaVlBvewmsV8rynZWIxuaAO0GsrT1zb+q5YxkHGJqIcaTY=
  on:
    tags: true
    repo: mariosant/imm
